### ISSUE TITLE
About the discriminator.

### ISSUE THREAD

**Issue by alaltera** [georgeguo-cn/DiCGAN#1]
Hello. I have a question for the discriminator. Your paper shows that the discriminator output dimension is 1, which represents the true and false probability, but the output dimension in the code is h (300), which is averaged after calculation. Is this consistent, or why? I look forward to your reply. Thank you!

**Comment by georgeguo-cn** [comment]
Thanks for your question, the output of the discriminator should be one-dimensional, we have uploaded a new version.

**Comment by alaltera** [comment]
Thank you for your reply. I tried to use a discriminator with an output dimension of 1 and an output dimension of 50, and finally took the calculated average as a loss, but I used the CFGAN model instead of DiCGAN. I have found that an output of 50 makes training more stable and exhibits better training results. When training the DiCGAN model, did you choose a discriminator with an output of 1 or an output of 300?

**Comment by georgeguo-cn** [comment]
Actually, we choose the discriminator with an output of 1 in training. 
We also found that training may be more stable when the output dimension of the discriminator is larger than 1 （such as 300）, but we adopted the conventional setting, that is, the output dimension is 1. 
The reason for the instability may come from the training of GAN.

**Comment by alaltera** [comment]
I understand. Thank you very much for your answer.
